INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Lanchonete', 27, 12);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Posto', 31, 18);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Joalheria', 15, 12);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Floricultura', 19, 21);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Pub', 12, 8);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Supermercado', 23, 6);
INSERT INTO PONTO_INTERESSE(PI_ID, PI_NOME, PI_COORD_X, PI_COORD_Y) VALUES (PI_SEQ.NEXTVAL, 'Churrascaria', 28, 2);